name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  artifacts:
    name: Artifacts
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        config:
          - os: "macOS-latest"
            dir: osx64
            arch: darwin-arm64
          - os: "ubuntu-latest"
            dir: linux64
            arch: linux-amd64
          - os: "windows-latest"
            dir: win64
            arch: windows-x64
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - run: mkdir -p ${{ matrix.config.dir }}
      - name: tar artifacts
        if: ${{ matrix.config.os != 'windows-latest' }}
        env:
          OUT_DIR: ${{ matrix.config.dir }}
          OS: ${{ matrix.config.os }}
        run: |
          import os
          src = os.environ['OUT_DIR']
          dst = "tf_client-0.1.${{ github.run_number }}-${{ matrix.config.arch }}.tar.gz"
          os.system("tar -czvf %s %s" % (dst, src))
        shell: python
      - uses: ncipollo/release-action@v1
        name: upload
        with:
          artifacts: "tf_client-0.0.1-${{ matrix.config.arch }}.tar.gz"
          allowUpdates: true
          replacesArtifacts: false
          commit: master
          tag: v0.0.1
